### ISSUE TITLE
Wyszukiwanie instytutów/działów przy dodawaniu sprawy

### ISSUE THREAD

**Issue by onetrueoninon** [virdiignis/PUT_COVID-19_Office_System#7]
Nie zawsze to wyszukiwanie działa, ale jeszcze nie znalazłam prawidłowości

**Comment by virdiignis** [comment]
Wyszukiwanie było przeprowadzone przez porównanie tekstu od początku. Zmieniłem to na test zawierania, więc wyszukiwanie powinno sprawiać teraz lepsze wrażenie.
