### ISSUE TITLE
System formularzy

### ISSUE THREAD

**Issue by onetrueoninon** [virdiignis/PUT_COVID-19_Office_System#9]
Weryfikacja tożsamości przeprowadzana jest poprzez potwierdzenie zgłoszenia przez adres w domenie Politechniki - należy zwrócić uwagę, że nie wszyscy pracownicy takie adresy posiadają. Często są oni zgłaszani przez swoich przełożonych, ale opcja ta całkowicie uniemożliwia im zgłoszenie swojego case'a przez formularz.

**Comment by virdiignis** [comment]
Osoby nieposiadające adresu w domenie put.poznan.pl muszą zostać ręcznie zweryfikowane w informatorze – droga zgłoszenia poprzez wysłanie maila na covid19@put.poznan.pl lub przez telefon pozostaje dla nich otwarta. Nie chcemy fałszywych zgłoszeń poprzez formularz, ani by służył spamerom do atakowania dowolnych adresów.

**Comment by virdiignis** [comment]
Btw. repozytorium systemu formularzy znajduje się pod adresem https://github.com/virdiignis/PUT_COVID-19_Forms_System, tam też należy zgłaszać błędy i uwagi go dotyczące.

**Comment by onetrueoninon** [comment]
Satysfakcjonuje mnie to wyjaśnienie, spasiba.

Btw. o 6:55 nie wpadłam, że formsy mają dedykowane issues.
